<template>
  <d-button>123</d-button>
  <i class="d-icon-edit"></i>
  <d-icon name="edit"></d-icon>
  <d-button-group>
    <d-button>123</d-button>
    <d-button>456</d-button>
  </d-button-group>
  <!-- <div class="affix-container" style="width: 500px; height: 300px"> -->
  <d-affix :offset="120">
    <d-button>affix</d-button>
  </d-affix>
  <!-- </div> -->
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <d-affix position="bottom" :offset="120">
    <d-button>affix</d-button>
  </d-affix>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
  <p>
    <d-button>456</d-button>
  </p>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'
export default defineComponent({
  name: '',
  setup() {
    return {}
  }
})
</script>
<style lang='scss'>
</style>
